name: CD Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  cd_deploy_test:
    name: CD Deploy to Test Job
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies + pytest-html
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Run pytest & generate HTML report
        run: |
		# write out the profile (here called "TEST")
		cat <<EOF > ~/.databrickscfg
		[TEST]
		host = https://adb-3205945681233138.18.azuredatabricks.net/
		azure_tenant_id = ${{ secrets.AZURE_TENANT_ID }}
		azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
		azure_client_secret = ${{ secrets.AZURE_CLIENT_SECRET }}
		EOF

      - name: Deploy to TEST
        run: |
          databricks bundle deploy \
            --target test \
            --profile TEST  
